cms_common: skip authentication on the 'Friendly' slot
rhboot/pesign pull request #101
Opened 2022-12-22 09:07 UTC by lcp

When finding a certificate in a 'Friendly' slot without the need of the private key, it is not necessary to authenticate the slot.

Signed-off-by: Gary Lin <glin@suse.com>

2023-02-06 21:41 UTC, frozencemetery requested changes
I don't feel that there's enough context present to review this PR.  That's not really your fault, as NSS doesn't have docs, but it does mean that it's not really clear what problem this fixes (or feature it enables?) or how.  Could you provide this information in commit message / code comments?

2023-02-10 02:14 UTC, lcp commented
Ok. I'll add a use case into the commit message.

2023-02-10 06:06 UTC, lcp commented
Updated the commit message as the following:

When finding a certificate in a 'Friendly' slot without the need of the
private key, it is not necessary to authenticate the slot.

For example, when the signed attributes and the raw signature are
created in a server and the user has the certificate, signkey.x509, and
tries to import them into myapp.efi:

  $ certutil -N -d nssdb -f passwd
  $ certutil -A -d nssdb -f passwd -n signkey -t CT,CT,CT \
      -i signkey.x509
  $ pesign -n nssdb -c signkey -i myapp.efi -o myapp.efi.signed \
      -d sha256 -I myapp.sattr -R myapp.sig

Since the "signkey" is 'Friendly', i.e. publicly readable, and the
private key is not needed, we can just skip the authentication and find
"signkey" in the slot.

2023-02-13 19:54 UTC, frozencemetery approved these changes

2023-02-13 19:54 UTC, merged