pesigcheck: Fix crash on digest match
rhboot/pesign pull request #90
Opened 2022-06-07 15:58 UTC by vhankala

Set selected_digest when the digest is found in db or dbx.
This fixes a crash in get_digest().

Signed-off-by: Visa Hankala <visa@hankala.org>

2022-06-08 19:10 UTC, frozencemetery commented
Thanks for the patch.  It would be good to put more information on the crash you see in the commit message.

Looking more at the code, I dislike the existing practice of using a signed integer for this at all.  I'd prefer a `struct digest param *` that's NULL when no set - at least that way we'd get a hard crash instead of accessing -1 sometimes.

(If you'd prefer not to perform that refactoring, please let me know and I'll take care of it.)

2022-06-08 19:16 UTC, frozencemetery requested changes
(Marking reviewed as above.)

2022-06-10 13:35 UTC, vhankala commented
> (If you'd prefer not to perform that refactoring, please let me know and I'll take care of it.)

I have not done that refactoring.

2022-06-10 18:37 UTC, frozencemetery approved these changes

2022-06-10 18:38 UTC, merged